"""Add cart, wishlist, and order models

Revision ID: 258e1872fb24
Revises: 264b8fd4e81a
Create Date: 2025-11-23 12:07:32.585190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '258e1872fb24'
down_revision: Union[str, Sequence[str], None] = '264b8fd4e81a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED', name='orderstatus', native_enum=False), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('customer_first_name', sa.String(length=100), nullable=True),
    sa.Column('customer_last_name', sa.String(length=100), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=False),
    sa.Column('delivery_city', sa.String(length=100), nullable=True),
    sa.Column('delivery_state', sa.String(length=100), nullable=True),
    sa.Column('delivery_postal_code', sa.String(length=20), nullable=True),
    sa.Column('delivery_country', sa.String(length=100), nullable=True),
    sa.Column('subtotal', sa.Numeric(), nullable=False),
    sa.Column('tax', sa.Numeric(), nullable=False),
    sa.Column('shipping', sa.Numeric(), nullable=False),
    sa.Column('discount', sa.Numeric(), nullable=False),
    sa.Column('total', sa.Numeric(), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('payment_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_created_at'), 'order', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_customer_email'), 'order', ['customer_email'], unique=False)
    op.create_index(op.f('ix_order_order_number'), 'order', ['order_number'], unique=True)
    op.create_index(op.f('ix_order_status'), 'order', ['status'], unique=False)
    op.create_index(op.f('ix_order_user_id'), 'order', ['user_id'], unique=False)
    op.create_table('cart_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_cart_user_product')
    )
    op.create_index(op.f('ix_cart_item_product_id'), 'cart_item', ['product_id'], unique=False)
    op.create_index(op.f('ix_cart_item_user_id'), 'cart_item', ['user_id'], unique=False)
    op.create_table('order_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('product_sku', sa.String(length=100), nullable=True),
    sa.Column('product_image_url', sa.String(length=500), nullable=True),
    sa.Column('unit_price', sa.Numeric(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_order_id'), 'order_item', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_item_product_id'), 'order_item', ['product_id'], unique=False)
    op.create_table('wishlist_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_wishlist_user_product')
    )
    op.create_index(op.f('ix_wishlist_item_product_id'), 'wishlist_item', ['product_id'], unique=False)
    op.create_index(op.f('ix_wishlist_item_user_id'), 'wishlist_item', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wishlist_item_user_id'), table_name='wishlist_item')
    op.drop_index(op.f('ix_wishlist_item_product_id'), table_name='wishlist_item')
    op.drop_table('wishlist_item')
    op.drop_index(op.f('ix_order_item_product_id'), table_name='order_item')
    op.drop_index(op.f('ix_order_item_order_id'), table_name='order_item')
    op.drop_table('order_item')
    op.drop_index(op.f('ix_cart_item_user_id'), table_name='cart_item')
    op.drop_index(op.f('ix_cart_item_product_id'), table_name='cart_item')
    op.drop_table('cart_item')
    op.drop_index(op.f('ix_order_user_id'), table_name='order')
    op.drop_index(op.f('ix_order_status'), table_name='order')
    op.drop_index(op.f('ix_order_order_number'), table_name='order')
    op.drop_index(op.f('ix_order_customer_email'), table_name='order')
    op.drop_index(op.f('ix_order_created_at'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
